const MASTER_DATA = {
    "Etoile one::christmas": { name: "Etoile one", price: 149000, template: "christmas" },
    "Etoile duo::christmas": { name: "Etoile duo", price: 349000, template: "christmas" },
    "Etoile four::christmas": { name: "Etoile four", price: 599000, template: "christmas" },
    "Christmas Hampers Tin::christmas": { name: "Christmas Hampers Tin", price: 159000, template: "christmas" },
    "Double choco oat::christmas": { name: "Double choco oat", price: 70000, template: "christmas" },
    "Raisin oat::christmas": { name: "Raisin oat", price: 70000, template: "christmas" },
    "Almond choco oat::christmas": { name: "Almond choco", price: 70000, template: "christmas" },
    "Double choco oat::hanniel": { name: "Double choco oat", price: 70000, template: "hanniel" },
    "Raisin oat::hanniel": { name: "Raisin oat", price: 70000, template: "hanniel" },
    "Almond choco oat::hanniel": { name: "Almond choco", price: 70000, template: "hanniel" },
    "Strawberry overnight oats::hanniel": { name: "Strawberry overnight oats", price: 42000, template: "hanniel" },
    "Double choco overnight oats::hanniel": { name: "Double choco overnight oats", price: 42000, template: "hanniel" },
    "Tiramisu overnight oats::hanniel": { name: "Tiramisu overnight oats", price: 42000, template: "hanniel" },
    "Custom tin cookie hamper::hanniel-dp": { name: "Custom tin cookie hamper", price: 65000, template: "hanniel-dp" },
    "Custom tin cookie hamper::hanniel-fi": { name: "Custom tin cookie hamper", price: 138000, template: "hanniel-fi" },
    "Lunar Bloom Tin::cny": { name: "Lunar Bloom Tin", price: 188000, template: "cny" },
    "Double choco oat::cny": { name: "Double choco oat", price: 70000, template: "cny" },
    "Raisin oat::cny": { name: "Raisin oat", price: 70000, template: "cny" },
    "Almond choco oat::cny": { name: "Almond choco", price: 70000, template: "cny" },
    "Kembang Pusaka::cnyhp": { name: "Kembang Pusaka", price: 599000, template: "cnyhp" },
    "Seri Kemala::cnyhp": { name: "Seri Kemala", price: 349000, template: "cnyhp" },
    "Double choco oat::cnyhp": { name: "Double choco oat", price: 70000, template: "cnyhp" },
    "Raisin oat::cnyhp": { name: "Raisin oat", price: 70000, template: "cnyhp" },
    "Almond choco oat::cnyhp": { name: "Almond choco", price: 70000, template: "cnyhp" },
};
